// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88iliNXVHxEKPaRdRx46sxfECaIVaIz0',
    appId: '1:17919061012:web:88df52da49a4fea92e0b01',
    messagingSenderId: '17919061012',
    projectId: 'budget-app-cb6db',
    authDomain: 'budget-app-cb6db.firebaseapp.com',
    storageBucket: 'budget-app-cb6db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDac2wcZlqxHKOw8ruvOkClNER3Cksit6s',
    appId: '1:17919061012:android:d1f5da3b5245aa9e2e0b01',
    messagingSenderId: '17919061012',
    projectId: 'budget-app-cb6db',
    storageBucket: 'budget-app-cb6db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEG2VHjaF-TWCqtngHiOCF6sgilnMdW4A',
    appId: '1:17919061012:ios:1599f1bd0e1805b22e0b01',
    messagingSenderId: '17919061012',
    projectId: 'budget-app-cb6db',
    storageBucket: 'budget-app-cb6db.appspot.com',
    iosClientId: '17919061012-49jj45bnrns6tdk93khqsk1qg9u71099.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEG2VHjaF-TWCqtngHiOCF6sgilnMdW4A',
    appId: '1:17919061012:ios:5b8ef78211b655a82e0b01',
    messagingSenderId: '17919061012',
    projectId: 'budget-app-cb6db',
    storageBucket: 'budget-app-cb6db.appspot.com',
    iosClientId: '17919061012-ntfrgq6q156md68g666hdfqnusub2hbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp.RunnerTests',
  );
}
